# 1. Create a 3x3x3 array with random values 

In [21]:
import numpy as np
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr1
arr2 = np.random.randn(3,3,3)
arr2

array([[[-0.27169565,  1.39901012,  0.5662323 ],
        [ 0.33019623,  0.67604465,  0.34604016],
        [ 1.38076405,  0.32081799,  0.99529495]],

       [[ 0.73272885, -0.29941427, -0.15377454],
        [ 1.01121567, -1.10305509,  1.32834138],
        [-0.23516442,  0.16727411,  1.45578974]],

       [[ 0.71827057, -0.9483431 , -0.98338936],
        [ 0.46163923,  1.73873685,  0.72982559],
        [-1.33453818, -0.26384767, -0.10895339]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [92]:
import pandas as pd

arr1 = np.arange(1,26)
arr1 = arr1.reshape(5,5)
arr1 = arr1.transpose()
print('original array was :\n',arr1)
arr1[:,0] = arr1[-1::-1,0]
print('diagonal elements are : ',np.diag(arr1))
print('required numbers below diagonal :\n ' ,arr1)




original array was :
 [[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
diagonal elements are :  [ 5  7 13 19 25]
required numbers below diagonal :
  [[ 5  6 11 16 21]
 [ 4  7 12 17 22]
 [ 3  8 13 18 23]
 [ 2  9 14 19 24]
 [ 1 10 15 20 25]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [108]:
arr1 = np.ones((8,8),dtype=int)

arr3 = np.ones_like(arr1)

for i in range(8):
    for j in range(8):
        if (i%2) == 0 :
            if (j%2) == 0 :
                arr3[i,j]=1
            else:
                arr3[i,j] = 0
        else:
            if (j%2) == 0 :
                arr3[i,j]=1
            else:
                arr3[i,j] = 0

                
arr3     
        

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [186]:
arr1 =np.arange(1,26).reshape(5,5)
arr1 =np.matrix(arr1)
print('original matrix is :\n',arr1)
arr1max, arr1min = arr1.max(), arr1.min()
arr1 = (arr1 - arr1min)/(arr1max - arr1min)
print("After normalization:")
print(arr1)


original matrix is :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
After normalization:
[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


# 5.  How to find common values between two arrays?

In [154]:
arr1 = np.array([[1,2,3,4],[5,6,4,8]])
arr2 = np.array([[4,11,3,7],[10,11,4,15]])
arr1[arr1==arr2]


array([3, 4])

# 6.How to get the dates of yesterday, today and tomorrow?

In [167]:
from datetime import date
from datetime import timedelta
today = date.today()
print('Todays Date is :',today)
yesterday = today -timedelta(days=1)

print('Yesterdays date was :',yesterday)
tomorrow = today +timedelta(days=1)
print('Tomorrows date is :',tomorrow)

Todays Date is : 2020-07-26
Yesterdays date was : 2020-07-25
Tomorrows date is : 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [184]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3,4],[5,6,7,8]])
x,y=a.shape
for i in range(x):
    for j in range(y):
        if a[i,j]!=b[i,j]:
            print("They are not Equal !!")
        break
else:
    print('They are Equal..!!')
        
        
    


They are Equal..!!


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [202]:
a = np.random.randn(10)
print('length of a is ',len(a))
amax = a.max()
print('Maximum value is :',amax)

for i in range(len(a)):
    if (a[i] == amax):
        a[i]=0
print('New Vector is :',a)

length of a is  10
Maximum value is : 1.236267225894594
New Vector is : [-1.05186912  0.79443982 -0.14662848  0.96473933 -1.3109792  -0.07302332
 -1.01325332 -0.54425176 -0.73090351  0.        ]


# 9. How to print all the values of an array?

In [206]:
a = np.array([1,2,3,4,5])
for i in range(len(a)):
    print(a[i],end=' ')

1 2 3 4 5 

# 10.Subtract the mean of each row of a matrix

In [211]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print('2D array is :\n',a)
mean = a.mean()
print('Mean of the array is :',mean)
result = a-mean
print('Result of the subtraction is :\n',result)

2D array is :
 [[1 2 3 4]
 [5 6 7 8]]
Mean of the array is : 4.5
Result of the subtraction is :
 [[-3.5 -2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5  3.5]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [230]:
a = np.array([1,2,3,4,5])
print('Random array is : ',a)
index = np.array([1,1,2,3])
print('Array of elements based on which the operation is to be carried out is :',index)
index = np.sort(index)
temp = []
for i in index:
    if i not in temp:
        temp.append(i)
print('Unique Elements of Index array is :',temp)
     
temp = np.array(temp)
for i in temp:
    a[i] = a[i]+1
            
print('new array is :',a)         

Random array is :  [1 2 3 4 5]
Array of elements based on which the operation is to be carried out is : [1 1 2 3]
Unique Elements of Index array is : [1, 2, 3]
new array is : [1 3 4 5 5]


# 12.How to get the diagonal of a dot product?

In [236]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10],[11,12],[13,14],[15,16]])
c = a.dot(b)
print('Dot product is :\n',c)
print('Diagonal of the dot product is :',c.diagonal())

Dot product is :
 [[130 140]
 [322 348]]
Diagonal of the dot product is : [130 348]


# 13.How to find the most frequent value in an array?

In [348]:
a= np.array([1,2,3,4,4,4,4,4,4,4,4,4,4,1,1,2,2,2,2,2,2,2])
a=np.sort(a)
temp = np.copy(a)
temp=np.sort(temp)
count=0
maxa =1
for i in a:
    for j in temp:
        if i ==j:
            count= count+1
            if count>maxa:
                maxa =count
                k=i
        else:
            count =0
print('Element which has max frequency is :',k)            
print('Maximum Frequency of element is :',maxa)        

Element which has max frequency is : 4
Maximum Frequency of element is : 10


# 14.How to get the n largest values of an array

In [291]:
a =np.array([1,2,3,1,2,3,4,5,6,7,8,9])
a= np.unique(a)
a= np.sort(a)
n = int(input(print('please input n value')))
a[-1:-(n+1):-1]
    

please input n value
None3


array([9, 8, 7])

# 15.How to create a record array from a regular array?

In [329]:
arr1 = np.array([('Vamsi',30,'IT'),('Priyanka',30,'Tech'),('Apoorv',30,'Chem')],dtype =[('Name','U16'),('Age','i8'),('Branch','U16')])
arr1['Age']
arr1 = arr1.view(np.recarray)
arr1.Name

array(['Vamsi', 'Priyanka', 'Apoorv'], dtype='<U16')